# Generated by Django 2.1.7 on 2019-11-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='kaam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('econtact', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Position')),
            ],
        ),
    ]
